env:
  TERM: xterm-256color

window:
  dimensions:
    columns: 72
    lines: 22

  padding:
    x: 8
    y: 8 

  dynamic_padding: false

  opacity: 1

  title: Alacritty

  class:
    instance: Alacritty
    general: Alacritty

scrolling:
  history: 10000

font:
  normal:
    family: EllographCF
    style: Medium

  bold:
    family: EllographCF
    style: Bold

  italic:
    family: EllographCF
    style: Italic

  bold_italic:
    family: EllographCF
    style: Bold Italic

  size: 10.0

  offset:
    x: 0
    y: 0

colors:
  primary:
    background: '0x010101'
    foreground: '0xB3B1AD'
  normal:
    black:   '0x213225'
    red:     '0xD54E53'
    green:   '0xB9CA49'
    yellow:  '0xE7C547'
    blue:    '0x79A6DA'
    magenta: '0xC397D8'
    cyan:    '0x70C0B1'
    white:   '0xf2faf6'

  bright:
    black:   '0x727474'
    red:     '0xD54E53'
    green:   '0xB9CA49'
    yellow:  '0xE7C547'
    blue:    '0x79A6DA'
    magenta: '0xC397D8'
    cyan:    '0x70C0B1'
    white:   '0xf2faf6'    

cursor:
  style: Block

key_bindings:
  - { key: V,         mods: Control|Shift, action: Paste                       }
  - { key: C,         mods: Control|Shift, action: Copy                        }
  - { key: Insert,    mods: Shift,         action: PasteSelection              }
  - { key: Key0,      mods: Control,       action: ResetFontSize               }
  - { key: Equals,    mods: Control,       action: IncreaseFontSize            }
  - { key: Plus,      mods: Control,       action: IncreaseFontSize            }
  - { key: Minus,     mods: Control,       action: DecreaseFontSize            }
  - { key: F11,       mods: None,          action: ToggleFullscreen            }
  - { key: Paste,     mods: None,          action: Paste                       }
  - { key: Copy,      mods: None,          action: Copy                        }
  - { key: L,         mods: Control,       action: ClearLogNotice              }
  - { key: L,         mods: Control,       chars: "\x0c"                       }
  - { key: PageUp,    mods: None,          action: ScrollPageUp,   mode: ~Alt  }
  - { key: PageDown,  mods: None,          action: ScrollPageDown, mode: ~Alt  }
  - { key: Home,      mods: Shift,         action: ScrollToTop,    mode: ~Alt  }
  - { key: End,       mods: Shift,         action: ScrollToBottom, mode: ~Alt  }
